#!/usr/bin/env bash
# Creates PID file, displays messages, handles signals
echo $$ > /var/run/myscript.pid

trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
